/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const translations = {
  en: {
    // Nav & Common
    appName: "Komal Creations & Training Center",
    tagline: "Fashion Designing • Custom Stitching • Traditional & Modern Embroidery",
    home: "Home",
    courses: "Courses",
    gallery: "Gallery",
    contact: "Contact",
    adminCheck: "Admin Panel",
    verifyCert: "Verify Certificate",
    enrollNow: "Enroll Now",
    toggleLang: "ਪੰਜਾਬੀ (Punjabi)",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    actions: "Actions",
    noData: "No entries available.",

    // Home Page
    heroTitle: "Learn the Art of Professional Dress Designing",
    heroSubtitle: "Empowering students in Nabha, Patiala with premium vocational skills in sewing, hand embroidery, painting, and modern boutique dressmaking.",
    exploreCourses: "Explore Professional Courses",
    activeClasses: "Join Active Batches",
    aboutTitle: "About Komal Creations",
    aboutText1: "Komal Creations & Training Center is a premier fashion learning center and bespoke designer boutique located in Nabha, Patiala, Punjab. Founded by expert designer Komalpreet Kaur, we offer highly practical, career-oriented certificates in simple stitching, traditional hand embroidery, textile painting, and elite boutique tailoring.",
    aboutText2: "Whether you want to start your own customized dress boutique, work as a professional designer, or learn stitching for personal creations, our training center offers localized bilingual classes (Punjabi & English) designed for students of all experience levels.",
    whyChooseUs: "Why Learn with Us?",
    why1Title: "Expert Personal Care",
    why1Desc: "Individual assistance and small batches designed to help each student learn drafting and sewing step-by-step.",
    why2Title: "Bilingual Curriculum",
    why2Desc: "All structural modules, templates, and instructions are explained beautifully in combined Punjabi and English.",
    why3Title: "Professional Certification",
    why3Desc: "Gain formal verification with searchable certificate numbers to unlock careers in boutiques and fashion design.",
    why4Title: "Boutique Ready Experience",
    why4Desc: "Learn commercial calculations, custom fittings, boutique operations, fabric selections, and trendy design cuts.",
    visitStudioBtn: "Visit Our Center in Nabha",

    // Courses Page
    coursesPageTitle: "Our Professional Training Courses",
    coursesPageSub: "Acquire high-demand vocational crafting skills with affordable monthly fees. Choose your ideal curriculum.",
    feesLabel: "Fees:",
    month: "month",
    durationLabel: "Duration:",
    stitchingTitle: "Simple Stitching Course",
    stitchingDesc: "Learn simple suits, palazzos, frock suits, kurtis, tops, neck styles, and basic stitching techniques.",
    embroideryTitle: "Hand Embroidery & Fabric Painting",
    embroideryDesc: "Traditional phulkari motifs, chain stitching, thread arts, fabric color mixing and textile patterns.",
    designTitle: "Designer Dresses & Boutique Mastery",
    designDesc: "Elite modern tailor operations, Western designer shirts, wedding gowns, lehengas, and commercial management.",
    enrollFormTitle: "Admission Registration Form",
    enrollFormSub: "Submit your details to reserve a seat. Our executive will reach out to schedule your demo class.",
    fullName: "Full Name",
    phone: "Phone Number (WhatsApp preferred)",
    email: "Email Address (Optional)",
    address: "Permanent Address",
    selectCourse: "Select Training Course",
    choose: "-- Click to Choose Course --",
    langPref: "Class & Notes Language Preference",
    prefEnglish: "English Study Material",
    prefPunjabi: "ਪੰਜਾਬੀ (Punjabi Standard)",
    enrollSubmit: "Submit Enrollment Application",
    enrolling: "Processing Enrollment...",
    enrollSuccess: "Congratulations! Your admission request has been sent successfully. We will contact you or WhatsApp you shortly.",

    // Gallery Page
    galleryPageTitle: "Student Works & Boutique Designs",
    galleryPageSub: "Browse through original hand-crafted ladies suits, elegant embroideries, and modern designer outfits stitched by our students.",
    allPics: "All Works",
    suitCategory: "Punjabi Suits",
    embCategory: "Embroidery Details",
    dressCategory: "Designer Attires",
    closeModal: "Close",

    // Contact Page
    contactPageTitle: "Connect With Our Team",
    contactPageSub: "Visit us for custom stitching consultations, direct boutique bookings, or course admissions.",
    addressTitle: "Our Training Center Address",
    addressVal: "Megh Colony, Aloharan Khurd, Nabha, Patiala, Punjab - 147201, India",
    phoneTitle: "Inquiries & WhatsApp",
    emailTitle: "E-mail Identity",
    instagramTitle: "Follow on Instagram",
    hoursTitle: "Instruction Hours",
    hoursVal: "Monday to Saturday: 9:00 AM – 5:00 PM (Sunday Closed)",
    mapPlaceholder: "Interactive Map Location Placeholder (Aloharan Khurd, Nabha)",
    sendMailTitle: "Send an Online Inquiry Message",
    sendMailSub: "Have questions about course timings, syllabus, or custom dress stitching? Write to us.",
    msgLabel: "Your Message",
    sendMsgBtn: "Send Professional Message",
    sending: "Sending Your Message...",
    contactSuccess: "Thank you! Your message has been recorded. Our training coordinator will call you back shortly.",

    // Login Page
    adminLoginTitle: "Admin Security Portal",
    adminLoginSub: "Authorized personnel login only.",
    username: "Admin Username",
    password: "Password",
    loginSubmit: "Access Dashboard",
    loggingIn: "Authenticating Securely...",
    loginError: "Please enter valid administration credentials.",

    // Verify Page
    verifyTitle: "Student Certificate Verification",
    verifySub: "Enter a student's verification code below to instantly inspect authentication status, transcripts, and course completion details.",
    enterCodePlc: "e.g., KCMA612",
    verifyBtn: "Verify Online",
    verifying: "Searching Database...",
    certValid: "Verified Authentic Student Certificate",
    studentName: "Student Full Name",
    issuedCourse: "Issued Training Course",
    certNo: "Certificate Serial Number",
    issueDate: "Issue Authorization Date",
    statusText: "Graduation Merit Status",
    completionStatus: "Completed Comfortably",
    notMatchTitle: "Verification Failed",
    notMatchDesc: "The provided certificate verification code was not found. Please review the printing and ensure punctuation matches exactly.",

    // Print & Beautiful layout Elements
    printTitle: "Vocational Qualification Certificate",
    certifiedBy: "This is to formally certify that",
    completedSuccess: "has successfully studied, practiced, and qualified all requirements for the professional curriculum of",
    certificateAt: "conducted at Komal Creations & Training Center, Nabha.",
    awardedOn: "Awarded with distinction and approved on:",
    authorizedSig: "Authorized Signatory",
    sealText: "ORIGINAL QUALITY ASSURANCE SEAL",
    verificationFoot: "To verify online, query the code at:",
    printNow: "Print Physical Copy",

    // Admin Dashboard
    dashboardTitle: "Boutique & Training Center Dashboard",
    tabSummary: "Stats Index",
    tabStudents: "Manage Students",
    tabEnrollments: "Enrollment Sheets",
    tabCourses: "Manage Curriculums",
    tabCertificates: "Issue Certificates",
    tabGallery: "Admin Gallery",
    tabMessages: "Visitor Inquiries",
    logout: "Log Out Admin",

    // Admin Details
    totalStudents: "Total Trained Students",
    totalEnrollments: "Active Registrations",
    totalCourses: "Created Modules",
    totalMessages: "Unread Messages",
    totalCertificates: "Granted Certs",

    addStudent: "Register New Student",
    editStudent: "Edit Student Records",
    addCourse: "Draft New Course",
    editCourse: "Modify Course Index",
    addPic: "Upload Gallery Attire",
    issueCertificateBtn: "Issue Graduate Certificate",
    
    confirmDelete: "Are you sure you would like to permanently delete this field? This process is irreversible.",
    saving: "Saving Changes...",
    savingBtn: "Save Database Record",
    cancel: "Cancel Operation",
    
    feeStatus: "Fee Status",
    courseStatus: "Active Status",
    paid: "Paid",
    pending: "Pending",
    halfPaid: "Half Paid",
    active: "Active",
    completed: "Completed",
    dropped: "Dropped",

    studentSearchPlc: "Search students by name, email or mobile...",
    courseNameEn: "Course Name (English)",
    courseNamePa: "Course Name (ਪੰਜਾਬੀ)",
    coursePrice: "Monthly/Course Fee (INR Rs)",
    courseDuration: "Duration (Months/Weeks)",
    descEn: "Syllabus Description (English)",
    descPa: "Syllabus Description (ਪੰਜਾਬੀ)",

    imageTitleEn: "Image Concept (English)",
    imageTitlePa: "Image Concept (ਪੰਜਾਬੀ)",
    imageUrlPlc: "Web Image URL"
  },
  pa: {
    // Nav & Common
    appName: "ਕੋਮਲ ਕ੍ਰਿਏਸ਼ਨਜ਼ ਐਂਡ ਟ੍ਰੇਨਿੰਗ ਸੈਂਟਰ",
    tagline: "ਫੈਸ਼ਨ ਡਿਜ਼ਾਈਨਿੰਗ • ਕਸਟਮ ਸਿਲਾਈ • ਪਰੰਪਰਾਗਤ ਅਤੇ ਆਧੁਨਿਕ ਕਢਾਈ",
    home: "ਮੁੱਖ ਪੰਨਾ",
    courses: "ਕੋਰਸਿਜ਼",
    gallery: "ਗੈਲਰੀ",
    contact: "ਸੰਪਰਕ",
    adminCheck: "ਐਡਮਿਨ ਪੈਨਲ",
    verifyCert: "ਸਰਟੀਫਿਕੇਟ ਵੈਰੀਫਿਕੇਸ਼ਨ",
    enrollNow: "ਦਾਖਲਾ ਲਓ",
    toggleLang: "English (ਅੰਗਰੇਜ਼ੀ)",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    success: "ਸਫਲਤਾ",
    error: "ਗਲਤੀ",
    actions: "ਕਾਰਵਾਈਆਂ",
    noData: "ਕੋਈ ਰਿਕਾਰਡ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",

    // Home Page
    heroTitle: "ਪੇਸ਼ੇਵਰ ਡਰੈੱਸ ਡਿਜ਼ਾਈਨਿੰਗ ਦੀ ਕਲਾ ਸਿੱਖੋ",
    heroSubtitle: "ਨਾਭਾ (ਪਟਿਆਲਾ) ਵਿੱਚ ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਸਿਲਾਈ-ਕਢਾਈ, ਹੱਥ ਦੀ ਕਢਾਈ, ਪੇਂਟਿੰਗ ਅਤੇ ਬੁਟੀਕ ਡਿਜ਼ਾਈਨਿੰਗ ਵਿੱਚ ਉੱਤਮ ਹੁਨਰ ਪ੍ਰਦਾਨ ਕਰਕੇ ਸਵੈ-ਨਿਰਭਰ ਬਣਾਉਣਾ।",
    exploreCourses: "ਸਾਡੇ ਡਿਜ਼ਾਈਨਿੰਗ ਕੋਰਸ ਵੇਖੋ",
    activeClasses: "ਨਵੇਂ ਬੈਚਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
    aboutTitle: "ਕੋਮਲ ਕ੍ਰਿਏਸ਼ਨਜ਼ ਬਾਰੇ ਜਾਣਕਾਰੀ",
    aboutText1: "ਕੋਮਲ ਕ੍ਰਿਏਸ਼ਨਜ਼ ਐਂਡ ਟ੍ਰੇਨਿੰਗ ਸੈਂਟਰ ਨਾਭਾ (ਪਟਿਆਲਾ, ਪੰਜਾਬ) ਵਿੱਚ ਸਥਿਤ ਇੱਕ ਪ੍ਰਮੁੱਖ ਫੈਸ਼ਨ ਸਿਖਲਾਈ ਕੇਂਦਰ ਅਤੇ ਡਿਜ਼ਾਈਨਰ ਬੁਟੀਕ ਹੈ। ਮਾਹਰ ਡਿਜ਼ਾਈਨਰ ਕੋਮਲਪ੍ਰੀਤ ਕੌਰ ਦੀ ਅਗਵਾਈ ਵਿੱਚ, ਅਸੀਂ ਸਧਾਰਨ ਸਿਲਾਈ, ਰਵਾਇਤੀ ਹੱਥ ਕਢਾਈ, ਫੈਬਰਿਕ ਪੇਂਟਿੰਗ ਅਤੇ ਬੁਟੀਕ ਲੈਵਲ ਸੂਟ ਮੇਕਿੰਗ ਦੇ ਬਿਹਤਰੀਨ ਕੋਰਸ ਕਰਵਾਉਂਦੇ ਹਾਂ।",
    aboutText2: "ਭਾਵੇਂ ਤੁਸੀਂ ਆਪਣਾ ਬੁਟੀਕ ਸ਼ੁਰੂ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ, ਫੈਸ਼ਨ ਉਦਯੋਗ ਵਿੱਚ ਨੌਕਰੀ ਕਰਨੀ ਹੈ, ਜਾਂ ਘਰੇਲੂ ਵਰਤੋਂ ਲਈ ਸਿਲਾਈ ਸਿੱਖਣੀ ਹੈ, ਸਾਡੇ ਸੈਂਟਰ ਦੀਆਂ ਕਲਾਸਾਂ ਪੰਜਾਬੀ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਦੋਵਾਂ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਬੜੇ ਹੀ ਆਸਾਨ ਤਰੀਕੇ ਨਾਲ ਪ੍ਰੈਕਟੀਕਲ ਕਰਵਾ ਕੇ ਸਿਖਾਈਆਂ ਜਾਂਦੀਆਂ ਹਨ।",
    whyChooseUs: "ਸਾਨੂੰ ਕਿਉਂ ਚੁਣਿਆ ਜਾਵੇ?",
    why1Title: "ਖਾਸ ਨਿੱਜੀ ਧਿਆਨ",
    why1Desc: "ਹਰ ਇੱਕ ਵਿਦਿਆਰਥੀ ਲਈ ਸੀਮਤ ਸੀਟਾਂ ਵਾਲੇ ਬੈਚ ਤਾਂ ਜੋ ਡਰਾਫਟਿੰਗ, ਕਟਾਈ ਅਤੇ ਸਿਲਾਈ ਆਸਾਨੀ ਨਾਲ ਸਮਝਾਈ ਜਾ ਸਕੇ।",
    why2Title: "ਦੋ-ਭਾਸ਼ਾਈ ਸਿਖਲਾਈ (Bilingual)",
    why2Desc: "ਕੋਰਸ ਦੀ ਸਾਰੀ ਜਾਣਕਾਰੀ, ਮਾਪ ਅਤੇ ਡਿਜ਼ਾਈਨ ਦੇ ਤਰੀਕੇ ਪੰਜਾਬੀ ਅਤੇ ਸਧਾਰਨ ਅੰਗਰੇਜ਼ੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮਝਾਏ ਜਾਂਦੇ ਹਨ।",
    why3Title: "ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਸਰਟੀਫਿਕੇਸ਼ਨ",
    why3Desc: "ਕੋਰਸ ਪੂਰਾ ਹੋਣ 'ਤੇ ਵੈਰੀਫਾਈਡ ਸਰਟੀਫਿਕੇਟ ਦਿੱਤਾ ਜਾਂਦਾ ਹੈ ਜਿਸ ਨੂੰ ਵੈੱਬਸਾਈਟ 'ਤੇ ਸਰਟੀਫਿਕੇਟ ਨੰਬਰ ਨਾਲ ਲੱਭਿਆ ਜਾ ਸਕਦਾ ਹੈ।",
    why4Title: "ਬੁਟੀਕ ਚਲਾਉਣ ਦਾ ਗਿਆਨ",
    why4Desc: "ਕੱਪੜੇ ਦੀ ਚੋਣ, ਗਾਹਕਾਂ ਦੇ ਮਾਪ ਦਾ ਹਿਸਾਬ, ਕਸਟਮ ਫਿਟਿੰਗਸ ਅਤੇ ਨਵੇਂ ਟਰੈਂਡੀ ਕੱਟਾਂ ਦੇ ਵਿਵਸਾਇਕ ਤਰੀਕੇ ਸਿੱਖੋ।",
    visitStudioBtn: "ਸਾਡੇ ਸੈਂਟਰ ਨਾਭਾ ਵਿਖੇ ਆਓ",

    // Courses Page
    coursesPageTitle: "ਸਾਡੇ ਪੇਸ਼ੇਵਰ ਟ੍ਰੇਨਿੰਗ ਕੋਰਸ",
    coursesPageSub: "ਬਹੁਤ ਹੀ ਕਿਫਾਇਤੀ ਫੀਸਾਂ 'ਤੇ ਫੈਸ਼ਨ ਡਿਜ਼ਾਈਨਿੰਗ ਦਾ ਲੋੜੀਂਦਾ ਹੁਨਰ ਹਾਸਲ ਕਰੋ। ਆਪਣਾ ਮਨਪਸੰਦ ਕੋਰਸ ਚੁਣੋ।",
    feesLabel: "ਫੀਸ:",
    month: "ਮਹੀਨਾ",
    durationLabel: "ਸਮਾਂ (ਦੌਰਾਨ):",
    stitchingTitle: "ਸਧਾਰਨ ਸਿਲਾਈ ਕੋਰਸ",
    stitchingDesc: "ਸਧਾਰਨ ਸੂਟ, ਪਲਾਜ਼ੋ, ਫਰਾਕ ਸੂਟ, ਕੁਰਤੀਆਂ, ਸਧਾਰਨ ਪੈਂਟ ਅਤੇ ਗਲੇ ਦੇ ਨਵੇਂ ਸਟਾਈਲਿਸ਼ ਡਿਜ਼ਾਈਨ ਸਿੱਖੋ।",
    embroideryTitle: "ਹੱਥ ਦੀ ਕਢਾਈ ਅਤੇ ਫੈਬਰਿਕ ਪੇਂਟਿੰਗ",
    embroideryDesc: "ਪਾਰੰਪਰਿਕ ਫੁਲਕਾਰੀ ਡਿਜ਼ਾਈਨ, ਜੰਜੀਰੀ ਕੰਮ, ਸ਼ੀਸ਼ਾ ਕੰਮ, ਧਾਗੇ ਦੀ ਕਾਰੀਗਰੀ ਅਤੇ ਸੂਟਾਂ 'ਤੇ ਕਲਰ ਪੇਂਟਿੰਗ।",
    designTitle: "ਡਿਜ਼ਾਈਨਰ ਡਰੈੱਸਸ ਅਤੇ ਹੋਰ ਸਾਰੇ ਸੂਟ",
    designDesc: "ਆਧੁਨਿਕ ਬੁਟੀਕ ਡਿਜ਼ਾਈਨ ਸਿਲਾਈ, ਵੈਸਟਰਨ ਟੌਪ, ਗਾਊਨ, ਲਹਿੰਗੇ, ਸ਼ਾਦੀ ਸੂਟ ਅਤੇ ਬੁਟੀਕ ਪ੍ਰਬੰਧਨ।",
    enrollFormTitle: "ਨਵਾਂ ਦਾਖਲਾ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਫਾਰਮ",
    enrollFormSub: "ਆਪਣੀ ਸੀਟ ਰਿਜ਼ਰਵ ਕਰਨ ਲਈ ਵੇਰਵੇ ਭਰੋ। ਸਾਡਾ ਸਹਿਯੋਗੀ ਡੈਮੋ ਕਲਾਸ ਲਈ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੇਗਾ।",
    fullName: "ਵਿਦਿਆਰਥੀ ਦਾ ਪੂਰਾ ਨਾਮ",
    phone: "ਫੋਨ ਨੰਬਰ (ਵਟਸਐਪ ਵਾਲਾ)",
    email: "ਈਮੇਲ ਐਡਰੈੱਸ (ਜੇਕਰ ਹੈ)",
    address: "ਪੱਕਾ ਪਤਾ (ਘਰ ਦਾ ਪਤਾ)",
    selectCourse: "ਸਿਖਲਾਈ ਕੋਰਸ ਦੀ ਚੋਣ ਕਰੋ",
    choose: "-- ਕੋਰਸ ਚੁਣਨ ਲਈ ਇੱਥੇ ਕਲਿੱਕ ਕਰੋ --",
    langPref: "ਪੜ੍ਹਾਈ ਅਤੇ ਨੋਟਸ ਦੀ ਭਾਸ਼ਾ ਪਸੰਦ",
    prefEnglish: "ਅੰਗਰੇਜ਼ੀ ਸਟੱਡੀ ਮਟੀਰੀਅਲ (English)",
    prefPunjabi: "ਪੰਜਾਬੀ ਮਟੀਰੀਅਲ (Punjabi)",
    enrollSubmit: "ਦਾਖਲਾ ਅਰਜ਼ੀ ਭੇਜੋ",
    enrolling: "ਅਰਜ਼ੀ ਪ੍ਰੋਸੈਸ ਹੋ ਰਹੀ ਹੈ...",
    enrollSuccess: "ਵਧਾਈਆਂ! ਤੁਹਾਡੀ ਦਾਖਲਾ ਅਰਜ਼ੀ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋ ਗਈ ਹੈ। ਅਸੀਂ ਜਲਦੀ ਹੀ ਫੋਨ ਜਾਂ ਵਟਸਐਪ ਰਾਹੀਂ ਸੰਪਰਕ ਕਰਾਂਗੇ।",

    // Gallery Page
    galleryPageTitle: "ਵਿਦਿਆਰਥੀਆਂ ਦੁਆਰਾ ਤਿਆਰ ਕੰਮ",
    galleryPageSub: "ਸਾਡੇ ਸੈਂਟਰ ਦੇ ਵਿਦਿਆਰਥੀਆਂ ਦੁਆਰਾ ਹੱਥੀਂ ਤਿਆਰ ਕੀਤੇ ਲੇਡੀਜ਼ ਸੂਟ, ਖੂਬਸੂਰਤ ਕਢਾਈਆਂ ਅਤੇ ਨਵੇਂ ਡਿਜ਼ਾਈਨਰ ਕੱਪੜੇ ਦੇਖੋ।",
    allPics: "ਸਾਰੀਆਂ ਤਸਵੀਰਾਂ",
    suitCategory: "ਪੰਜਾਬੀ ਸੂਟ (Suits)",
    embCategory: "ਕਢਾਈ ਦੇ ਰੂਪ (Embroidery)",
    dressCategory: "ਡਿਜ਼ਾਈਨਰ ਡਰੈੱਸਸ (Western)",
    closeModal: "ਬੰਦ ਕਰੋ",

    // Contact Page
    contactPageTitle: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    contactPageSub: "ਕੱਪੜੇ ਸਿਲਾਈ ਬੁਕਿੰਗ, ਸੂਟਾਂ ਦੀ ਡਿਜ਼ਾਈਨਿੰਗ ਜਾਂ ਨਵੇਂ ਕੋਰਸਾਂ ਵਿੱਚ ਦਾਖਲਾ ਲੈਣ ਲਈ ਮਿਲੋ।",
    addressTitle: "ਸਾਡੇ ਚੱਲ ਰਹੇ ਸੈਂਟਰ ਦਾ ਪਤਾ",
    addressVal: "ਮੇਘ ਕਲੋਨੀ, ਆਲੋਹਰਾਂ ਖੁਰਦ, ਨਾਭਾ, ਪਟਿਆਲਾ, ਪੰਜਾਬ - 147201, ਭਾਰਤ",
    phoneTitle: "ਫੋਨ ਅਤੇ ਵਟਸਐਪ ਪੁੱਛਗਿੱਛ",
    emailTitle: "ਈਮੇਲ ਸੰਪਰਕ ਲਿੰਕ",
    instagramTitle: "ਇੰਸਟਾਗ੍ਰਾਮ (Instagram)",
    hoursTitle: "ਖੁੱਲ੍ਹਣ ਅਤੇ ਸਿਖਲਾਈ ਦਾ ਸਮਾਂ",
    hoursVal: "ਸੋਮਵਾਰ ਤੋਂ ਸ਼ਨੀਵਾਰ: ਸਵੇਰੇ 9:00 ਵਜੇ – ਸ਼ਾਮ 5:00 ਵਜੇ (ਐਤਵਾਰ ਛੁੱਟੀ)",
    mapPlaceholder: "ਆਲੋਹਰਾਂ ਖੁਰਦ ਨਾਭਾ ਮੈਪ ਚਿੱਤਰ (Google Map Place)",
    sendMailTitle: "ਸਵਾਲ ਪੁੱਛਣ ਲਈ ਆਨਲਾਈਨ ਸੁਨੇਹਾ ਭੇਜੋ",
    sendMailSub: "ਕੋਰਸ ਦੇ ਸਮੇਂ, ਸਿਲੇਬਸ ਜਾਂ ਸੂਟ ਸਿਲਾਈ ਸੰਬੰਧੀ ਕੋਈ ਵੀ ਸਵਾਲ ਹੈ? ਸਾਨੂੰ ਲਿਖੋ।",
    msgLabel: "ਤੁਹਾਡਾ ਸੁਨੇਹਾ",
    sendMsgBtn: "ਸੁਨੇਹਾ ਭੇਜੋ",
    sending: "ਸੁਨੇਹਾ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    contactSuccess: "ਧੰਨਵਾਦ! ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਸੁਰੱਖਿਅਤ ਹੋ ਗਿਆ ਹੈ। ਸਾਡਾ ਸਿਖਲਾਈ ਕੋਆਰਡੀਨੇਟਰ ਜਲਦੀ ਹੀ ਕਾਲ ਕਰੇਗਾ।",

    // Login Page
    adminLoginTitle: "ਐਡਮਿਨ ਸੁਰੱਖਿਆ ਪੋਰਟਲ",
    adminLoginSub: "ਕੇਵਲ ਅਧਿਕਾਰਤ ਐਡਮਿਨ ਲੌਗਇਨ ਕਰ ਸਕਦੇ ਹਨ।",
    username: "ਐਡਮਿਨ ਯੂਜ਼ਰਨਾਮ",
    password: "ਪਾਸਵਰਡ (Password)",
    loginSubmit: "ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ ਖੋਲ੍ਹੋ",
    loggingIn: "ਪ੍ਰਮਾਣਿਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    loginError: "ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਐਡਮਿਨ ਯੂਜ਼ਰਨਾਮ ਅਤੇ ਪਾਸਵਰਡ ਭਰੋ।",

    // Verify Page
    verifyTitle: "ਵਿਦਿਆਰਥੀ ਸਰਟੀਫਿਕੇਟ ਵੈਰੀਫਿਕੇਸ਼ਨ",
    verifySub: "ਕੋਮਲ ਕ੍ਰਿਏਸ਼ਨਜ਼ ਦੇ ਕਿਸੇ ਵੀ ਜਾਰੀ ਕੀਤੇ ਸਰਟੀਫਿਕੇਟ ਦੀ ਅਸਲੀਅਤ ਪਰਖਣ ਲਈ ਹੇਠਾਂ ਵੈਰੀਫਿਕੇਸ਼ਨ ਕੋਡ ਦਰਜ ਕਰੋ।",
    enterCodePlc: "ਉਦਾਹਰਨ: KCMA612",
    verifyBtn: "ਆਨਲਾਈਨ ਵੈਰੀਫਾਈ ਕਰੋ",
    verifying: "ਡੇਟਾਬੇਸ ਵਿੱਚ ਖੋਜ ਚੱਲ ਰਹੀ ਹੈ...",
    certValid: "ਵੈਰੀਫਾਈਡ ਅਸਲੀ ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਮਾਣਿਤ ਹੈ",
    studentName: "ਵਿਦਿਆਰਥੀ ਦਾ ਪੂਰਾ ਨਾਮ",
    issuedCourse: "ਸਿਖਾਇਆ ਗਿਆ ਕੋਰਸ",
    certNo: "ਸਰਟੀਫਿਕੇਟ ਸੀਰੀਅਲ ਨੰਬਰ",
    issueDate: "ਜਾਰੀ ਕਰਨ ਦੀ ਮਿਤੀ",
    statusText: "ਗ੍ਰੈਜੂਏਸ਼ਨ ਮੈਰਿਟ ਨਤੀਜਾ",
    completionStatus: "ਕੋਰਸ ਸਫਲਤਾਪੂਰਵਕ ਕੋਮਲ ਕ੍ਰਿਏਸ਼ਨ ਤੋਂ ਪਾਸ",
    notMatchTitle: "ਵੈਰੀਫਿਕੇਸ਼ਨ ਫੇਲ੍ਹ",
    notMatchDesc: "ਇਹ ਵੈਰੀਫਿਕੇਸ਼ਨ ਕੋਡ ਸੈਂਟਰ ਦੇ ਰਿਕਾਰਡਸ ਵਿੱਚ ਨਹੀਂ ਮਿਲਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਅੱਖਰਾਂ ਨੂੰ ਧਿਆਨ ਨਾਲ ਦੇਖੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",

    // Print & Beautiful Layout Elements
    printTitle: "ਵਿਵਸਾਇਕ ਯੋਗਤਾ ਪ੍ਰਮਾਣ ਪੱਤਰ",
    certifiedBy: "ਇਹ ਤਸਦੀਕ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਕਿ",
    completedSuccess: "ਨੇ ਸਫਲਤਾਪੂਰਵਕ ਪੜ੍ਹਾਈ, ਟ੍ਰੇਨਿੰਗ ਅਤੇ ਸਾਰੇ ਮਾਪਦੰਡ ਪੂਰੇ ਕਰ ਕੇ ਹੇਠ ਲਿਖੇ ਕੋਰਸ ਚ ਯੋਗਤਾ ਪ੍ਰਾਪਤ ਕੀਤੀ ਹੈ:",
    certificateAt: "ਇਹ ਟ੍ਰੇਨਿੰਗ ਕੋਮਲ ਕ੍ਰਿਏਸ਼ਨਜ਼ ਐਂਡ ਟ੍ਰੇਨਿੰਗ ਸੈਂਟਰ, ਨਾਭਾ ਵਿਖੇ ਪ੍ਰਾਪਤ ਕੀਤੀ ਗਈ।",
    awardedOn: "ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ ਕਰਨ ਦੀ ਮਿਤੀ ਅਤੇ ਪ੍ਰਵਾਨਗੀ:",
    authorizedSig: "ਅਧਿਕਾਰਤ ਹਸਤਾਖਰ",
    sealText: "ਅਸਲੀ ਗੁਣਵੱਤਾ ਮੋਹਰ",
    verificationFoot: "ਆਨਲਾਈਨ ਚੈੱਕ ਕਰਨ ਲਈ ਵੈੱਬਸਾਈਟ 'ਤੇ ਸਰਚ ਕਰੋ:",
    printNow: "ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਿੰਟ ਕਰੋ",

    // Admin Dashboard
    dashboardTitle: "ਬੁਟੀਕ ਅਤੇ ਟ੍ਰੇਨਿੰਗ ਸੈਂਟਰ ਸੁਪਰਵਾਈਜ਼ਰ",
    tabSummary: "ਸਾਰਾਂਸ਼ ਮੈਟ੍ਰਿਕਸ",
    tabStudents: "ਵਿਦਿਆਰਥੀ ਪ੍ਰਬੰਧਨ",
    tabEnrollments: "ਦਾਖਲਾ ਰਿਕਾਰਡਸ",
    tabCourses: "ਕੋਰਸਾਂ ਦੇ ਸਿਲੇਬਸ",
    tabCertificates: "ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ ਕਰੋ",
    tabGallery: "ਗੈਲਰੀ ਫੋਟੋਜ਼",
    tabMessages: "ਆਏ ਹੋਏ ਸੁਨੇਹੇ",
    logout: "ਲੌਗ ਆਉਟ (ਐਗਜ਼ਿਟ)",

    // Admin Details
    totalStudents: "ਕੁੱਲ ਰਜਿਸਟਰਡ ਵਿਦਿਆਰਥੀ",
    totalEnrollments: "ਕੁੱਲ ਹੋਏ ਦਾਖਲੇ",
    totalCourses: "ਚੱਲ ਰਹੇ ਕੋਰਸਿਜ਼",
    totalMessages: "ਪ੍ਰਾਪਤ ਹੋਏ ਸੁਨੇਹੇ",
    totalCertificates: "ਜਾਰੀ ਕੀਤੇ ਸਰਟੀਫਿਕੇਟ",

    addStudent: "ਨਵਾਂ ਵਿਦਿਆਰਥੀ ਦਰਜ ਕਰੋ",
    editStudent: "ਵਿਦਿਆਰਥੀ ਰਿਕਾਰਡ ਸੋਧੋ",
    addCourse: "ਨਵਾਂ ਕੋਰਸ ਸ਼ਾਮਲ ਕਰੋ",
    editCourse: "ਕੋਰਸ ਸੂਚੀ ਬਦਲੋ",
    addPic: "ਨਵੀਂ ਡਰੈੱਸ ਫੋਟੋ ਜੋੜੋ",
    issueCertificateBtn: "ਨਵਾਂ ਸਰਟੀਫਿਕੇਟ ਬਣਾਓ",
    
    confirmDelete: "ਕੀ ਤੁਸੀਂ ਯਕੀਨਨ ਇਸ ਨੂੰ ਹਮੇਸ਼ਾ ਲਈ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ? ਇਹ ਕਾਰਵਾਈ ਵਾਪਸ ਨਹੀਂ ਲਈ ਜਾ ਸਕਦੀ।",
    saving: "ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ ਹੋ ਰਹੇ ਹਨ...",
    savingBtn: "ਡੇਟਾਬੇਸ ਵਿੱਚ ਸੇਵ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    
    feeStatus: "ਫੀਸ ਦੀ ਸਥਿਤੀ",
    courseStatus: "ਕੋਰਸ ਸਟੇਟਸ",
    paid: "Paid (ਭੁਗਤਾਨ ਸਫਲ)",
    pending: "Pending (ਬਕਾਇਆ)",
    halfPaid: "Half Paid (ਅੱਧੀ ਫੀਸ)",
    active: "Active (ਚਾਲੂ)",
    completed: "Completed (ਪੂਰਾ ਹੋ ਗਿਆ)",
    dropped: "Dropped (ਬੰਦ)",

    studentSearchPlc: "ਵਿਦਿਆਰਥੀ ਦਾ ਨਾਮ, ਈਮੇਲ ਜਾਂ ਫੋਨ ਨਾਲ ਖੋਜੋ...",
    courseNameEn: "ਕੋਰਸ ਦਾ ਨਾਮ (ਅੰਗਰੇਜ਼ੀ 'ਚ)",
    courseNamePa: "ਕੋਰਸ ਦਾ ਨਾਮ (ਪੰਜਾਬੀ 'ਚ)",
    coursePrice: "ਮਹੀਨਾਵਾਰ/ਕੋਰਸ ਫੀਸ (ਰੁਪਏ 'ਚ)",
    courseDuration: "ਕੋਰਸ ਦਾ ਸਮਾਂ (ਮਹੀਨੇ/ਹਫ਼ਤੇ)",
    descEn: "ਕੋਰਸ ਸਿਲੇਬਸ ਜਾਣਕਾਰੀ (ਅੰਗਰੇਜ਼ੀ)",
    descPa: "ਕੋਰਸ ਸਿਲੇਬਸ ਜਾਣਕਾਰੀ (ਪੰਜਾਬੀ)",

    imageTitleEn: "ਫੋਟੋ ਦਾ ਟਾਈਟਲ (ਅੰਗਰੇਜ਼ੀ)",
    imageTitlePa: "ਫੋਟੋ ਦਾ ਟਾਈਟਲ (ਪੰਜਾਬੀ)",
    imageUrlPlc: "ਵੈੱਬਸਾਈਟ ਫੋਟੋ ਲਿੰਕ (URL)"
  }
};
